# Generated by Django 3.2.7 on 2021-10-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniNavbarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shog_images')),
                ('text', models.CharField(blank=True, max_length=2555, null=True)),
                ('name', models.CharField(blank=True, max_length=2555, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='title',
            new_name='collection_name',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
        migrations.AddField(
            model_name='footer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shog_images'),
        ),
        migrations.AddField(
            model_name='footer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='brand_images',
            field=models.ImageField(blank=True, null=True, upload_to='shog_images'),
        ),
        migrations.AddField(
            model_name='settings',
            name='collection_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='latest_blog_images',
            field=models.ImageField(blank=True, null=True, upload_to='shog_images'),
        ),
        migrations.AddField(
            model_name='settings',
            name='latest_blog_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='save_up',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='shog_images'),
        ),
    ]
