# Generated by Django 3.2.7 on 2021-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_auto_20211001_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedCard',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='category_id',
            new_name='subcategory_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.ManyToManyField(to='ecom_app.NavbarModel'),
        ),
        migrations.AddField(
            model_name='navbarmodel',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='navbarmodel',
            name='category_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='redcard_image',
            field=models.ImageField(blank=True, null=True, upload_to='shog_images'),
        ),
        migrations.AddField(
            model_name='settings',
            name='redcard_name',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='redcard_text',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='redcard_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
